---
title: "Attention to Online Channels across the Path to Purchase: An Eye-Tracking Study"

abstract: |

  These days, consumers display what is known as omnichannel behaviour; that is, the combined use of digital and physical channels providing them with multiple points of contact with firms. We combine the Stimulus-Organism-Response model and visual attention theory in order to study how customers attention to digital channels vary across different purchasing tasks. We use eye-tracking techniques to observe attention in an experimental setting. The experimental design comprises four purchasing tasks in four different product categories, and measures attention to the website and time spent on each task along with several control variables. The results show that shoppers attend to more areas of the website for purposes of website exploration than for performing purchase tasks. The most complex and time-consuming task for shoppers is the assessment of purchase options. The actual purchase and post-purchase tasks require less time and the inspection of fewer areas of interest. Personal involvement also plays a role in determining these patterns by increasing attention to the product area.

bibliography: bib/mybibfile.bib
csl: bib/elsevier-harvard.csl

output:
  word_document:
    keep_md: yes
    reference_docx: docs/ECRAWORD.docx



---

**Keywords**

_Customer journey, purchase task, eye-tracking, channel perception, experimental design_


Introduction
==========================

```{r include=FALSE}
library(kableExtra)
```

Analysis of the web customer's  experience is an increasingly important area of  research, not only because online retailing is now a basic feature of all sectors (in 2017, online sales worldwide grew by 24.8% with respect to the previous year and made up 10.2% of total retail sales worldwide [@Statista2019]), but because these marketing channels have also gained importance as platforms for communication and the distribution of services in an omnichannel environment [@Verhoef2015].

Consumer behaviour in such a context is becoming ever more complex, as customers use combinations of these multiple channels and points of contact with firms along what is known as the customer journey in order to satisfy their needs and purchase requirements [@Cassab2009]. A recent study involving a sample of 46,000 customers of a US retailer revealed that the vast majority (73%) use a combination of physical and digital channels to do their shopping [@Sopadjieva2017]. Another study conducted in 2016 in the Spanish fast fashion sector, showed that 60% of the customers were omnichannel shoppers  [@Chocarro2018]. 

Analizing this multitude of points of contact between consumers-companies and the information flow generated in these interactions is a top priority both for business and academia.  For example, the Marketing Science Institute points to the omni-channel phenomenon as one of the five marketing research priorities for the period 2018-2020  [@MarketignS2018] with other importance rising trends, as data flow from the Internet of Things (IoT) that interconnects people and objects in anytime, anyplace, with anything and anyone, using any path/network and any service [@Wang2017d]. Therefore, the understanding of how today’s consumer purchasing process evolves is essential for firms faced with the design and management of such channels and points of contact [@Beck2015].

There are various discernible stages along the customer’s journey through the purchasing process [@Neslin2006a]: the pre-purchase stage, in which the consumer seeks and analyses information prior to making a choice; the purchase stage, in which the consumer makes the purchase; and the post-purchase stages, which include, for example, the use of customer services or customer review sites. Consumers’ aims change and vary in complexity as they progress through the different stages [@Neslin2006a; @Verhoef2007].

As they go through these stages fulfilling their aims, consumers respond to the stimuli presented by the various channels, in other words, the so-called "atmospherics" [@Kotler1973]. The literature has used the term atmospherics to refer to the elements of the shopping environment that affect the consumer’s purchasing process. @Turley2000 offer a review of over 60 studies linking consumer behaviour to point-of-sale atmospherics, including a diversity of factors relating to inner and outer store appearance, store design, atmosphere, layout, colours and sounds, etc.

A pre-requirement of any response is attention to the stimulus, which is a largely unconscious process [@sandage1946; @Kellogg1980]. Consumers’ attention is a scarce resource for which companies compete [@Davenport2001]. A major part of retailers’ work is spent trying to draw the customer’s attention [@Puccinelli2009]. The research about the role of the attentional processes has been mainly concentrated on the area of advertising [@Belanche2017;@Lee2012; @Brasel2008; @Pieters2004; @Dreze2003; @Wedel2000; @Rayner2001] and to a minor extent on websites processing due to its later introduction [@Hasan2016; @Wang2014; @Velasquez2013; @shiwedel2013; @Leuthold2011; @Liu2011; @Lindgaard2006a; @Richard2005, among others]. There are studies that combine exposure to advertisements during the search in an online store [@Ahn2018a]. 

Prior research suggested that consumers will act differently when the have different tasks in mind [@Hong2004]. In the online environment, when users visit a website, their attention to the stimuli varies according to what they are aiming to achieve, which depends, in turn, on which stage of the purchasing process they are engaged in [@Rowley2000]. @Leuthold2011 show, for example, how customers’ web navigation strategies vary according to the complexity of the task, and retailers may therefore need to tailor their web designs to match different customer tasks. The same study reveals that the longer the task requires, the greater the cognitive load [@Leuthold2011] and this depends on the complexity of the task.

A scheme presented by @Huizingh2000, shows that website stimuli can be broken down into different levels. At level one they split into two groups: design features and content features. At level two, the content features include commercial information, product information, transaction information, and other content, such as entertainment elements, of less direct relevance on commercial websites. This information is presented on different sections of the website or so-called areas of interest (AOI), the main ones being the header, the product area and the navigation menu.

Thus, the objective of this paper is to examine precisely how the consumer attention process in the different AOIs on a website varies according to which of the three stages of the purchasing process the consumer is engaged in. In more detail, we aim to:

1.	Analyse the effect of the stage in the purchasing process on the time taken to complete the task: Does task completion time vary with each stage?  
2.	Analyse the effect of the stage in the purchasing process on the AOIs visited: Do the AOIs visited vary with each stage?  
3.	Analyse the effect of the stage in the purchasing process on the exploration pattern: Does the exploration pattern vary with each stage?  

This paper contributes to the literature with a novel analysis of variations in attention processes in digital environments in the three stages of the purchasing process using observational techniques and eye-tracking methods. The customer’s experience along the customer journey is internal and subjective [@Meyer2007] and therefore difficult to measure through declarative responses as in a questionnaire. This paper adopts eye-tracking as an attention-measuring tool. Eye tracking is described by @Lemon2016 as a useful means to explore more deeply into the experiences of the customer throughout the customer journey. The use of eye-tracking for attention measurement is nothing new [@Wedel2015]. However, the analysis of observational data alone could lead us to overlook relationships with other key variables such as the effect of the online purchasing experience or category involvement. 

Another contribution of this paper, therefore, is to investigate the attention process by performing a joint analysis of eye-tracker data and declarative feedback from a questionnaire.

In the following section, we provide a conceptual framework for the study and present the propositions. Section 3 contains the research design, and section 4 the results, discussion and modelling process, and our conclusions are presented in the final section.

# Conceptual framework and propositions

The stimulus-organism-response (S-O-R) paradigm from the field of environmental psychology posits that the various aspects of the environment act as stimuli (S) that affect the internal states (O) of people, which in turn, drive their behavioural responses (R) [@LinYan2017]. External Stimuli (S) involve different aspects from the environmental factors and conditions, which can be divided in social factors, design factors, and ambient factors [@Herrando2018]. The term “organisms” (O) is used to refer to the inner states of perceptions, feelings, and thinking exercises [@Luqman2017]. These states result in specific behavioural responses (R): the approach or avoidance behaviours of the consumer [@Ettis2017]. The S-O-R framework was proposed by @Mehrabian1974, and later applied to the retail context by @Rossiter1982 and to online retailing by @eroglu2001. 

In a different research stream, attention is a cognitive phenomenum that has been studied since late XIX century and can be conceived as the way of processing the vast amount of information with which people are confronted, prioritizing some aspects of information while ignoring others [@naatanen2018attention]. These attentional processes include visual attention, auditory attention, spatial attention and phenomena as selective attention, divided attention and distraction [@Pashler2016]. 

Attentional processes related to the visual stimuli are specially relevant. As @Wedel2008 point out “…visual attention is important in its own right. First, … visual attention is not only a gate,  but …, a key coordinating mechanism that serves to maintain information processing and other goals over time”. The visual marketing attention theory [@Wedel2008] differentiates between bottom-up and top-down sources as determining factors that drive the attentional processes related to the visual marketing stimuli. Bottom-up factors that affect the attention result from the physical features of the visual stimuli to which the consumers are exposed. Contrarily, top-down factors are related to individuals’ unique aspects such as expectations, objectives and emotions. These are personal characteristics affecting the attentional process. The attentional process is linked to the so-called downstream effects: learning, preference formation and choice and eventually, sales.

The model of visual attention is closely related to the S-O-R framework. In fact, the so-called bottom-up factors in the visual marketing theory by Wedel and Pieters (2008) are equivalent to the term External Stimuli in the S-O-R framework and the term “atmospherics” by @eroglu2001. Moreover, the bottom-up factors are a more general term for the two moderators included in the S-O-R model developed by Eroglu (2001). The downstream effects in the theory of attention to visual marketing can be divided in, first, inner states included in the Organism term, and second, Response states.   
In this research, we combined both frameworks in a more integrative model of response to atmospheric in online retailing. This model is presented in Figure 1:

----- Insert Figure 1 around here-------

In this model, the online shopping environment includes all the features of a given website. We can use the term “atmospherics” as general term for bottom-up factors. Web atmospherics are "...the conscious designing of Web environments to create positive affect and/or cognitions in surfers in order to develop positive consumer responses" [@Dailey2004a]. The model designed by @eroglu2001 classifies stimuli as task-relevant (product descriptions, prices, service conditions, product images, etc.) or task-irrelevant (colours, outlines, fonts, animations, etc.) 

These features are able to capture subject’s attention even in a non-actively searching condition of the consumer [@Wolfe1998].  The research devoted to attention to bottom-up factors using the visual marketing attention theory has also been oriented to study navigation strategies [@Dreze2003], appearance evaluation [@Lindgaard2006a; @Manippa2019], product presentation [@shiwedel2013], web atmospherics [@Richard2005; @Dailey2004a] and visual vs text information [@Cortinas2019]. Moreover, it is probable that the attentional process in the online framework varies as a function of the product category in the store [@shiwedel2013; @Leuthold2011; @Wang2014].

In this framework, subject’s top-down factors are factors such as the engagement with the product, online the acquaintance of the brand,  purchase task [@Rayner2001], or experience [@Samant2016]. Studies have shown that also other personal characteristics such as gender and age can influence attention to web sites [@Huang2018a, @Castilla2016].

In this paper we put our focus in two factors and their relationship: a top-down factor, namely, the purchase task and a bottom-up one: the information in the different AOIs of the web site.

Customers’ online behaviour varies according to the task they are engaged in. @Neslin2006a present a conceptual framework accommodating these perspectives and including three distinct main stages (search, purchase and after-sales) through which the consumer progresses after initial need-recognition, and during which he or she develops perceptions and preferences regarding the available channels. In the multichannel shopping context, a specific channel may be used in combination with others for the completion of a single purchase task, as is the case with web-rooming and show-rooming behaviour [@Beck2015; @Verhoef2015] and consumers’ channel preferences at each stage will also be influenced by their perceptions and preferences with respect to other options. It is also well documented in the literature that these tasks imply different degrees of cognitive burden and that more the complex tasks take longer to complete [@Wang2014]. 

Our first proposition, therefore, is:

**Proposition 1**. Website task completion time varies with task complexity, being longer for website exploration or the evaluation of purchase options than it is for actual purchase once the evaluation and search stages are complete.


Regarding the AOIs, @VanDuyne2003 define four key features of web design patterns: navigation area, brand content area, product content area and related links, the first three being the most important features of an e-commerce site. The layout and appearance of these areas are included in the design features, while the number of menu levels, depth of description, and others, are content features [@Huizingh2000; @Katz2003]; and both types are key influencers of website quality perception [@Al-Qeisi2014]. According to @Huizingh2000 “… content refers to the information, features, or services that are offered in the Web site; design, to the way the content is made available for Web visitors”. These content features are among the website-quality assessment tools identified and developed by IT and marketing researchers [@Chiou2010]. However, as noted by @Dedeke2016, website quality measurements usually integrate evaluations of website content features with others, such as speed and ease of use, or security, thereby complicating the task of analyzing their individual impact on consumer perceptions through the different stages of the path to purchase.

We can distinguish three main AOIs in an e-commerce web site.  The first on is the the header, which serves to define intention and content [@Holzschlag1998] and usually includes at least the name of the firm and, often, contact details. The header presents the company identity and brand logo. @Huizingh2000 refers to this and the product area as “marketing information areas”. The usefulness of the information will depend on the goal of the user, since the company’s identity may be irrelevant when navigating for purposes other than brand assessment. Thus, our second proposition states that:

**Proposition 2**. The header draws more attention and has a greater attention retention capacity and appeal when the user’s goal is website evaluation.

Next comes the key feature of a web page, the content, which, in B2C e-commerce sites, is located in the product area [@VanDuyne2003]. Information presentation in this area is critical for success [@Blanco2010]. According to @badre2002shaping, consumers expects products to be presented in much the same way as in a store, therefore the function and layout of the content area are similar to those of a shop window. As in the case of the header, however, attention levels in this area depend on the stage the consumer has reached in the purchase process, since product information is more necessary when evaluating and selecting options and for purchase task. Our third proposition, therefore, states as follows:

**Proposition 3**. The product area draws more attention and has greater attention retention capacity and appeal when the user’s goal is to evaluate the options and make a purchase.

The last key content feature is the navigation menu linking the user to the various internal pages of the website [@Yu2002]. This menu often has links to transactional information [@Huizingh2000], enabling access to the details of payment, shipping, return and other company policies. This sort of information may be more relevant at certain points in the transaction process and during overall evaluation of a specific site and less relevant for tasks relating to the evaluation of options. Thus, our fourth and last proposition states that:

**Proposition 4**. The service navigation menu commands more attention and has greater attention-grabbing and retention capacity during general exploration tasks and post-purchase tasks.

To conclude it is worth to mention those subject-dependent top-down factors influencing the attentional process such as the product involvement and online consumer experience. Product involvement is dependent on the consumers’ inherent needs, values and interests [@Zaichkowsky1985] and leads to an attentive state of mind that makes consumers more capable to process information [@Belanche2017; @Yoo2004]. On the other hand, online experience can create automaticity allowing habitual behaviors to be performed easily and quickly [@Wood2002]. This variables are considered to be additional subject characteristics affecting attentional process. 


# Research design

We test the above propositions by means of an experimental design. 

## Subjects and design

The research team recruited a random selection of 58 students from the fourth year of a degree course in Business Administration and Management from a university in Spain, who were them invited to a quiet laboratory without distractions and with controlled lighting conditions, where the data were to be collected. The choice of students may have an impact in the ay have an impact on the representativeness of our sample. However, there were several reasons suggesting that restricting the survey population to university students may be a minor problem. 25 to 34 year-olds make up the second largest segment (20.6%) of online purchasers in Spain in 2017, while the higher education population accounts for 34.3% [@ONTSI2018]. The product categories selected for the experimental tasks (sport shoes, mobile phone, ball-point pens, hard disks) are popular as online purchases among university students. A further circumstance is that previous studies have used the eye-tracking method to collect attention and fixation data during website tasks also used students as their subjects [@shiwedel2013; @Djamasbi2010; @Reutskaja2011; @Velasquez2013; @Leuthold2011] no although this is not the case in ad attention studies, where randomly-selected consumer samples are used [@Wedel2000; @Pieters2004].

This study uses an intra-subject design including four tasks (exploration, search, purchase, after sale) x four webs (sport shoes, mobile phone, ball-point pens, hard disks). This design has the advantage of controlling both for individual effects and for potential bias from the learning effect, which appears as the subjects progress through the required tasks [@Gentile1972]. Thus, all subjects are required to perform all four tasks and to visit all four stores (categories), but the task-store pairs are random combinations, such that no subject repeats the same task in the store in order to avoid interference from the learning effect.

## Materials

### Materials: web sites and AOIs

The experimental design was implemented by creating four simulated web stores, one for each of the four different product categories. Such simulation is not new to this type of research [@Leuthold2011; @Wang2014] and, although it reduces the degree of realism, it enables stricter control of other effects that might bias the results. It is a natural-looking e-commerce website layout enabling unambiguous location of the three AOIs as found in most countries worldwide [@Bernard2004]. Thus, the first AOI, the header showing the company identity, appears centre top and has a menu with contact details, the "Home" button on the left and the shopping cart on the right. The second AOI, the product offer, occupies centre-screen below the header. It has the appearance of a shop-window displaying product names, images of the goods and prices and add-to-cart buttons below. The third AOI, services, appears on the left below the header. We use the classification of AOI that is shown in Figure 2.

----------- Insert Figure 2 around here---------------

The product category can affect both time spent completing the task and how much attention is paid to the web page. This effect is mitigated by including these four different product categories with different degrees of risk and including both search and experience products [@Mitra1999]. The four categories are sports shoes, mobile phones, ball-point pens and hard disks. The same layout is used for all four stores, with variation in the colours but in no other features so as to avoid other potential biases. 

Images of all four web stores are provided in Annex 1.

### Materials: tasks definitions

Before task definition, qualitative interviews were conducted following a pre-test. The tasks are analogous to those used for each stage in previous studies [@shiwedel2013; @Leuthold2011; @Wang2014; @Reutskaja2011]. One task per stage is set plus one more for control purposes. The individuals face four tasks: 

- Task 1 Exploration Task (control): "rate the website for overall appeal"

- Task 2 Search Task: "visit the website and select from those offered the product which most appeals to you based on the information provided"  

- Task 3 Purchase Task: "add option X to the shopping cart"  

- Task 4 Post-sales: "find how to track your order"  

## Procedure

The study took place in April 2018. A random sample of 58 students is recruited by the research team. Eligible recruits are shown into the laboratory and seated at individual computer terminals where they are to perform the 4 tasks and complete a questionnaire. After calibration, the questionnaire becomes accessible and the tasks can begin. As an incentive, participants receive numbers in a draw for a 20€ Amazon shopping voucher. Given the profile, the sample is highly homogeneous with regard to age (mean age 24.8, with a standard deviation of 4.7) and occupation (94% were full-time students). More than half (60%) are women. 

----------------- Insert figure 3 around here ----------------- 

The procedure is shown in Figure 3. Each subject is randomly assigned to randomly-formed task/category pairs, such that each subject completes all four tasks and visits the four stores but the category in which each subject completes each task, and the order in which the tasks are completed are different for each subject. Store-task pair assignment and questionnaire implementation require another platform, in this case, the Qualtrics  online platform. The questionnaire is linked to the four web stores such that, when the task for a certain category comes up on screen and the subject presses the store access button, the time spent in the store up to the first click is registered and the subject returns to the questionnaire. 

We do not explicitly measure the success or failure of each task, as the subjects return to the questionnaire when they click anywhere on the screen. However, we measure this dimension implicitly for the four tasks as we ask the participants to rate the attractiveness of the webpage in the first task, to select the chosen product in the second task and to rate how difficult the task has been for them in the case of tasks 3 and 4. 

Data collection, including eye tracker instrument calibration, questionnaire completion and associated tasks take an approximate total of 15 minutes per person. Subjects are accompanied by a researcher throughout this process. 

## Method

This experiment enables us to obtain observational (eye-tracking) data and declarative feedback (questionnaire responses) from each subject. Subjects’ level of attention across task types is measured by means of purpose-designed eye-tracking hardware comprising cameras and infra-red light. The specific choice of hardware for this study is The Eye Tribe Tracker. According to its manufacturers, The Eye Tribe Tracker has an average accuracy of 0.5º, a spatial resolution of 0.1º (rms) and an average frame rate of 30 Hz. The system monitors the subject’s gaze throughout the trial and registers eye fixations according to a specified spatial dispersion criterion. 

A fixation is defined as a quasi stable position of the eye for a minimum of 200 milliseconds. The requirement for a quasi stable position requires that the angular dispersion of the eye is below 1º. The fixation check procedure filters out noise in the gaze data. The procedure only records fixations within the selected AOIs; thereby outliers in the gaze patterns are filtered out. Once the trial is complete, the gaze position coordinates and time patterns across the four tasks are taken and the subject’s fixation times are recorded and classified by AOI and type of task. We compute attention indicators such as the number of gaze fixations on each area of interest (to show the relative importance of each area) and transfers between AOIs (exploration pattern). Data on transitions between areas for each task are used to create individual AOI transfer matrices.

This information is completed with declarative feedback from the questionnaire to control for potentially unobserved subject characteristics that might affect attention and time spent on task. The questionnaire includes information about purchase habits, category involvement and sensitivity to brands, prices and services. Finally, subject characteristics, such as online shopping experience, and demographics are included for control purposes (see full questionnaire in Annex 2) . The individual attention patterns obtained by eye-tracking are linked to the declarative data from the questionnaire by a unique code generated by Qualtrics for each questionnaire. The metrics employed in this study are:

- **Task completion time**: task completion time in seconds.

- **Total fixations by AOI***: subject total fixations weighted by the relative surface area of the AOI and by the subject’s total number of fixations on the task. 

- **Probability of Transfers between AOI**: we calculate  ARANTXA

- **Involvement with the category**: This measure was obtained by means of a questionnaire.  Respondents were asked to indicate on a scale of 1-7 their level of agreement (1-Disagree strongly, 7-agree strongly) with three statements: “My Knowledge of X (name of product category) is very good, “It is important for me to make the right choice when shopping for X (name of product category)” and “I find shopping for X (name of product category) interesting”. The involvement construct was based on factor analysis of these three questionnaire items (Annex 2, Q6.1, Q6.2 and Q6.3) for each of the four categories. The Cronbach’s Alpha scale reliability coefficient is 0.69 for the sports shoes category, 0.81 for the mobile phones, 0.77 for the ball-point pens, and 0.73 for the hard disks (Cronbach, 1951). 

- **Ease with online information seeking**: This measure was obtained by means of a questionnaire.  Respondents were asked to rate their degree of ease in finding information through the Internet (0-extremely low; 10-Extremely high).

- **Online shopping experience**: This measure was obtained by means of a questionnaire.  Respondents were asked to rate their degree of ease in shopping through the Internet (0-extremely low; 10-Extremely high).



# Results and discussion

## Descriptive results

Figure 4 shows the box plots for time spent per task. It can be seen that the task requiring the longest time on average is the choice of product option (Task 2) (20 seconds on average) followed by the website exploration task (Task 1). The purchase task (Task 3)  and the order tracking task (Task 4) take less time on average.

Figure 5 shows the so-called “heat map” for each task in the case of the first store, the sport shoes store, which provides a visual representation of the attention scores per area. The maps show how the total number of fixations is distributed across the screen, with the deeper red areas indicating which parts of the screen attracted the highest numbers of fixations and the green areas those that drew least attention. It can be seen at a glance that attention is more dispersed during the website exploration task (Task 1), more concentrated on the product area during the information seeking task (Task 2), close attention to the specific option which has to be located for adding it to the cart during the purchase task (Task 3), and more attention to the side menu during the post-purchase or order-tracking task (Task 4). We also include heatmaps for the three other stores in Annex 2. It can be seen that inspecting the four stores leads to similar conclusions.

—————– Insert Figure 4 around here —————–

—————– Insert Figure 5 around here —————–


Figure 6 shows the numerical distribution of fixations per area, per task. Figure 6 shows that AOI A, which relates to brand identity (Header), presents fewer fixations than the other two areas and only receives higher attention during the exploration task (Task 1). The service menu area (area B) presents more fixations during the post-purchase task (Task 4), while the product area (area C) draws more attention during the options evaluation (Task 2) and purchase tasks (Task 3). 

—————– Insert Figure 6 around here —————–

As supplementary material, we provide slow-motion video images of subjects’ fixation patterns during the various tasks.

—————– Insert link to video 1, 2, 3 and 4—————–

The exploration video (Task 1), for example, shows how subjects transfer their attention between the three AOIs, beginning in the product area, before moving to the header and finally to the services menu. In the purchase task (Task 3), however, (the required product is third in the bottom row) after a brief exploration of the header and side menu, the subject’s attention fixates on the product area until the required product is located (purchase task video). See also the two example videos for the information-seeking (Task 2) and post-purchase tasks (Task 4).

With respect to feedback from the questionnaire, Table 1 gives a summary of the descriptive data for category involvement indicators and familiarity with online search of information and purchase.

—————– Insert Table 1 around here —————–

Sports shoes and mobile phones are both high-interest products. The hard disk, despite being the least known, is a high-importance and high-interest product due to its price. The opposite is true of ball-point pens, which are low-importance and low-interest products. The mobile phone is the category that generates most interest. The values for “ease with online information seeking and purchase processes” are high with very low standard deviation. 

## Modelling process (I)

Although in the descriptive analysis, we observe differences in the attention to the AOIs according to the task, in order to dig deeper into these relationships, we construct more general models that consider jointly the effect not only of the task, but also of the product category and personal characteristics included in the questionnaire. 

We construct three different models with three dependent variables: time spent of each subject on the task, number of fixations made by each subject while engaged in each task and the probability of transfer between AOIs in the each individual transfer matrix. The number of observations is the same for all models, a panel with 232 observations (number of subjects: 58  x number of task: 4). 

As in all these models, the same individual provides four observations, fixed effects models are used in all cases to account for this intra-subject correlation [@Carey2001] as we allow the constant term for each model to be different by subject and correlated with the regressor matrix. The models for time and total fixations are fixed effects regression models, as the dependent variables are continuous, while the models for transitions probabilities are fixed effects logistic regressions as the dependent variable varies between 0 and 1 [@agresti2003categorical].

The independent variables are the same ones already mentioned in section 3.4 for all models: task, product category, involvement with each category, ease with online information seeking and internet shopping experience. 

### Modelization 1: Time spent on task 

The model to be estimated for task completion time takes the following form:

**Model 1: Task Completion time**  

$y_{ij}=\alpha_{i}+\sum_{j=1}^4\beta_jTask_{ij} + \sum_{z=1}^4{\gamma_zCat_z}+\rho_1 Inv_{i}+ \rho_2 Search_{i}+ \rho_3 Purchase_{i} +e_{ij}$


\hfill [1]

$\alpha_{i}=\alpha+u_i$ \hfill [2]

\normalsize


where:

$y$ is task completion time in seconds, as per readings obtained from the eye-tracking experiment and the store link script 

$i$ is the subject, with  $i=1....58$ 

$j$ is the task subindex and the dummies are $1$: exploration $(Task_1)$, $2$: information seeking $(Task_2)$, $3$: purchase $(Task_3)$ y $4$: post purchase $(Task_4)$

$\alpha_{i}$ is the constant term for the model, which varies with the subject

$\beta_{j}$ are the parameters for the effect of the task relative to the control 0 (website exploration)

$\gamma_z$: parameters for the category effect, where the dummies are $Cat_1$: sports shoes, $Cat_2$: mobile phones, $Cat_3$: ball-point pens, $Cat_4$: hard disks

$Inv_{i}$: subject $i$'s involvement with the category in which the task is performed, based on questionnaire feedback

$Search_{i}$: subject $i$'s ease with online information seeking, based on questionnaire feedback

$Purchase_{i}$: subject $i$'s ease with online shopping, based on questionnaire feedback

$\rho_1$ parameter for subject’s level of involvement with the category based on factor analysis of three questionnaire items 

$\rho_2$ parameter for subject’s level of ease with online information seeking

$\rho_3$ parameter for  ease with online shopping

$e_{ij}$ and $u_j$ are the estimation error terms


We apply a linear mixed-effects estimation in R (v3.4.4) [@bates2014lme4].

-------- Insert Table 2 around here-----------

Table 2 shows the results of this estimation. The results suggest that task completion time varies considerably, according to the desired goal, around a global mean of 20’. Thus, information-seeking takes significantly longer than exploration (parameter 4.299), while the two simpler tasks, purchase and after sales, take significantly less time than either of the aforementioned (parameters -8.762 and -8.620).  These findings are consistent with the first proposition that the website task completion time is longer for exploration or the evaluation of purchase options than it is for the actual purchase.

With respect to the category effect, it should first be noted that, after controlling for the task effect, the time spent on the task is no shorter in the categories presented last (ball-point pens and hard disks) than in those presented first (sports shoes), which suggests that there are no serious problems deriving from the learning effect in this design. The only significant effect, which is found in the mobile phone category, can be interpreted as the result of its being the highest-interest category in average terms. Finally, the observed effect for ease with online information seeking and online shopping is close to zero, possibly due to the high homogeneity of the subject sample in this respect.

### Modelization 2: Gaze patterns across AOIs

Next, differences in levels of attention across the various AOIs are analyzed by aggregating all of each subject’s fixations on the first AOI, labelled A (header and upper menu), on AOI B (service menus) and AOI C (products).  Given the size differences between AOIs, total fixations are weighted by the relative surface area of the AOI and by the subject’s total number of fixations on the task. Three equations are estimated, one per AOI,  for $k=1,2,3$ to measure the level of attention to the three areas of interest while controlling for product category and individual characteristics:

\vspace{0.3cm}

**Model 2: Attention by AOIs: Total fixations by AOI**

\vspace{0.3cm}

$y_{ijk}=\alpha_{ik}+\sum_{j=1}^4{\beta_{jk}Task_{jk}}+\sum_{z=1}^4{\gamma_{zk}Cat_z}+\rho_{1k}Inv_{i}+\rho_{2k} Search_{i}+ \rho_{3k} Purchase_{i}+e_{ijk}$ \hfill [3]

$\alpha_{ik}=\alpha+u_i$ para $k=1,2,3$ \hfill [4]

\normalsize
where:

$y$ is the total number of fixations made by subject $i$ while engaged in task $j$ en AOI $k$ 

$i$ is the subject where $i=1....58$ 

$j$ is the task subindex where the dummies are $1$: exploration $(Task_1)$, $2$: information seeking $(Task_2)$, $3$: purchase $(Task_3)$ and $4$: after sales $(Task_4)$

$k$ is the area of interest, where 1 is the header, 2 is the side menu, and 3 is the content area

$\alpha_{k}$ is the constant term for the exploration area, which varies with the subject and the AOI

$\beta_{jk}$ are the parameters for the task effect in AOI $k$

$\gamma_{zk}$: parameters for the category and AOI effects, where the dummies are $Cat_1$: sports shoes, $Cat_2$: mobile phones, $Cat_3$: ball-point pens, $Cat_4$: hard disks

$Inv_{i}$: subject $i$'s involvement with the category in which the task is performed

$Search_{i}$: subject $i$'s ease with online information seeking 

$Purch._{i}$: subject $i$'s ease with online shopping 

$\rho_{1k}$ parameter for the subject’s category involvement in AOI k, based on factor analysis of three questionnaire items

$\rho_{2k}$ parameter for ease with online information seeking

$\rho_{3k}$ parameter for ease with online shopping

$e_{ijk}$ and $u_j$ are the error terms 


The three equations, one for each AOI, are estimated as linear mixed-effects models R (v3.4.4) [@bates2014lme4].

———— Insert Table 3 around here ————

The first three columns after the row names show the parameters for the fixations on AOI A, which, based on the negative statistical significance of the parameters of the AOI dummies, is more important in the website exploration tasks (baseline task, Task 1) than in the purchase-related tasks, particularly the actual purchase (Task 3). Columns 5, 6 and 7 give the estimates for attention to AOI B, (the menu), which is much more important in post-purchase tasks (Task 4), although it also draws a greater number of fixations during exploration tasks (Task 1) than during options evaluation (Task 2) and purchase (Task 3). From the last three columns it can be seen that AOI C, is, as expected, the focus of attention when evaluating options and making the purchase. These findings are consistent with the second, third and fourth propositions.

Regarding the effects of the control variables, although the attention patterns for AOI A show no significant differences across categories, the level of attention to the services menu (third, fourth and fifth columns) is significantly higher in the sports shoes category (presented in first place) than in the ball-point pen category (presented last but one), which might suggest a learning effect in this AOI. In this case, the origin of the differences cannot be identified. In the product AOI (last three columns), the only significant effect is a higher level of attention in the ball-point pen category. There are no observable effects from category involvement or ease with the online environment, except on attention levels to the header, where the effect of ease with online search is significant at the 5% level, and the menu area, where the effect of ease with online shopping is significant at the 5% level.

### Modelization 3: Exploration patterns

Finally, the dependent variable in the exploration pattern models is the probability of transfer between AOIs in the individual transfer matrix, where the minimum and maximum probabilities are 0 and 1, respectively, which means that a linear model is inadequate, so mixed effects logistic regression is used instead [@agresti2003categorical].

The models in this case use the same independent variables as in the previous cases, but each probability of transfer between AOIs is expressed as:

**Model 3**: Exploration patterns. Transitions between AOIs

$Prob(y_{ij}=1|X_{ij}) = \frac{exp(b_{0}+b_{1j}X_{1ij}+...+b_{zj}X_{ijz})}{1+exp(b_{0}+b_{1j}X_{1ij}+...+b_{zj}X_{ijz})}$ 

where:

$Prob(y_{ij}=1|X_{ij})$ ) is the probability of subject $i$'s attention relocating from one AOI to another in task $j$, subject to all the variables.

Exploration levels and patterns are analyzed by calculating the between-AOI transfer probability matrices [@Gehrer2018] shown in Figure 7, where the diagonal indicates the probability of fixation remaining in a given AOI, while the cells above and below the diagonal indicate the probability of between-AOI transfers during each task. 

------------Insert Figure 7 around here-------------

Overall, it can be seen that the probability of transfer is highest during exploration (Task 1), lowest in the post-purchase stage (Task 4), and not very high during the search (Task 2) and purchase stages (Task 3), except in the content area. The diagonals in all four matrices indicate the expected effects, except in the case of the post-purchase task, where, although the service menus in Area of Interest B show, as expected, the highest probability of attention retention (0.484), retention is also high (0.370) in content area C. This effect may be due to the interest generated by the content AOI, where the product information is richer and more varied and includes images, which have greater attention-grabbing capacity than text [@Yandandul2018; @Hausman2009].

————- Insert Table 4A around here ————-

Table 4A shows the model estimates for transfers from AOI A. The first model presented is for the probability of remaining in A, which is found to be higher during exploration than during the other tasks. Across categories, the upper menu has less attention-retaining capacity in the ball-point pen category, possibly due to this being a low-interest product. In terms of transfer probabilities, there is a greater chance of the shopper returning from the menu area to the header during the exploration stage than there is during either of the purchase tasks, but there is equal probability of it happening during the exploration and post-purchase tasks. 

Although the header is not relevant during a post-purchase task, subjects unconsciously switch their attention to it as frequently as they do during the exploration task. With respect to transfers from AOI C, the chances of attention shifting back to the header are greatest during exploration, given that, once the product or menu area has been reached, the header is no longer task-relevant.

Table 4B shows the three models for transitions to AOI B (lateral menu). 

————- Insert Table 4B around here ————-

The models for AOI B in the first three columns show that the probability of prolonged fixation on this area is much higher during the post-purchase tasks (Task 4) and much lower during purchase (Task 3) and evaluation (Task 4). The high cross-category variation observed in relation to the attention given to this area might indicate a learning effect. This is one of the limitations of this type of experimental design, which precludes the testing of individual category effects. 

Category involvement, meanwhile, negatively influences the attention-retaining capacity of AOI B: subjects with higher category involvement are more likely to switch from area B to more category-related areas. The capacity of this area to draw attention away from the header is equal across the exploration and post-purchase tasks and lower in the evaluation and purchase tasks. With regard to the last three columns, the probabilities of this area drawing attention away from the content area are very slight, with no significant cross-task variance, and the signs are as expected.

————- Insert Table 4C around here ————-

Finally, the attention-retaining capacity of the product area (AOI C) is higher during the options evaluation (Task 2) and purchase tasks (Task 3) and lower during the post-purchase task (Task 4), although, even in the latter, it plays an important role, as observation has shown, and fixation probability is higher during the associated tasks. 

Here, also, a category effect is observed. It could be due to learning, but also to other effects, since the effect reaches its highest value in association with ball-point pens, which are third in the presentation sequence. Involvement also has a positive effect, as reflected by the longer fixation durations observed in this area. The capacity of area C to draw attention away from area A is higher during exploration and lower during the post-purchase stage, as might be expected, while the capacity of any other area to attract attention away from area C shows no cross-task variation.


# Concluding remarks

In this paper we study how attention processes to the AOI of an online establishment vary depending on the different purchasing tasks. As our first contribution, we take an integrative theoretical approach considering the both Stimulus-Organism-Approach framework and the Visual Marketing Attention theory. 
This paper contributes to the analysis of the online shopping experience in an omnichannel environment by exploring cross-task variation in online shoppers’ attention patterns using eye-tracking techniques and combining this data (times, fixations and transfers) with declarative measures (feedback from a questionnaire) in an intra-subject experimental design.

Eye tracking metrics are particularly useful for measuring perceptive processes and they have been used to study cognitive processes [@Reutskaja2011], and attention to in-store [@Pieters2004] and online advertising stimuli [@Dreze2003; @Lee2012]. However, most of this literature does not control the effect of other characteristics of the individual, such as their involvement or experience which is a second contribution of this paper.

Our analysis shows that when subjects are just exploring a website, time-spent values and fixation values in all areas of interest are higher, and between-area attention transfers are more numerous. When subjects are evaluating purchase options, they spent more time and also, fixations are concentrated in the most task-relevant area, i.e., the product area. Subjects’ attention patterns when purchasing the selected option are similar to those observed when they are seeking information, although the time-spent values are lower, because the task is less complex. Finally, the post-purchase task is associated with low time-spent values and high fixation on the relevant menu; but attention transfer is more frequent, due to stimuli from other areas. We can say that this task is less powerful retaining attention than the other three ones. So, during the post-purchase task, which is the one which stimulates least interest and involvement, subjects are more likely to transfer their attention to task-irrelevant areas (product area and header), which shows that these areas can play an important role at any stage of the shopping process. 

Thus, our results also show how data on attention processes can prove useful when it comes to managing the increasingly complex consumer journey even in the final stages of a purchasing process (the post purchase stage), when additional stimuli can encourage a new purchase or at least create a more positive brand image. Although the transfer of attention towards adjacent areas is only momentary, it still has usefulness potential, as shown in @Lindgaard2006a where 50 milliseconds are long enough for evaluation to take place. After-sale visits to the webpage, for example, are an opportunity to draw attention to new stimuli, as our results show that transfers of attention to other areas are most frequent at this stage. Similarly, the header can still help to reinforce brand recognition in after-sale visits to the website. Managers should also concentrate on the product content area when trying to develop brand image, as this area is the main focus of attention during all tasks.

Category involvement also affects these patterns. Higher involvement increases attention to the product area, thus showing that motivated shoppers process product -related information more thoroughly. No noteworthy variation is observed in relation to ease with online information seeking and with shopping online, possibly because of the homogeneity of the sample in this respect. This might indicate a direction for future research.

Thinking of future research, as the literature has shown, images and text do not have the same attention-grabbing potential [@Liu2011]. We wonder whether these two factors play different roles at different stages in the shopping process and consider it an interesting question for future research. Another issue that is not covered by this paper is how attention patterns influence the final purchase choice, or other behavioural variables.

As a last suggestion, it might be interesting to explore variation in relation to product-category attributes, such as complexity, and whether they require sensory or non-sensory [@Trijp1996] evaluation. Although our experimental design is not suited to measuring category effects, the observed signs of variation in relation to the degree of product-category interest point to another potentially fruitful line of research.


\clearpage


References {#references .unnumbered}
==========

